### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by torsava** [fedora-infra/supybot-fedora#50]
Hi, is Python 3 compatibility planned in the future?

**Comment by puiterwijk** [comment]
The problem for this would be that supybot is not python3 compatible.
A quick Google did show me a fork at https://github.com/ProgVal/Limnoria that's supposedly python3-capable, so I would say that getting that looked at and possible Fedora package updated by that would be a first step.

I can look at this sometime in the future, and will keep this ticket open so that I keep track of that, but if anyone else would do this, that'd be welcome as well.

**Comment by encukou** [comment]
In case you were wondering why this bug was filed: it's because automation told us that all your Python dependencies in Fedora are ported. It turns out the [supybot-fedora spec file](http://pkgs.fedoraproject.org/cgit/rpms/supybot-fedora.git/tree/supybot-fedora.spec) is (IMO) slightly wrong.
The spec lists only `/usr/bin/supybot` as a dependency. This would be OK if the binary was only called, but if you need supybot the Python module, it would be more appropriate to depend on `supybot`.

If Limnoria is packaged, it might end up providing `/usr/bin/supybot` (with compatible functionality, but using Python 3).

**Comment by ryanlerch** [comment]
Done as part of https://github.com/fedora-infra/supybot-fedora/pull/65
